# Generated by Django 3.1.1 on 2020-10-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_comment_approved_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=100)),
            ],
        ),
    ]
