# Generated by Django 3.1.1 on 2020-10-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_subtitle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubTitle',
            new_name='Title',
        ),
    ]
